name: cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dockerize" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - run: git_hash=$(git rev-parse --short "$GITHUB_SHA")
      - run: sh dockerize.sh "${{ github.sha }}" "${{secrets.DOCKER_USERNAME}}"
      - run: sh dockerize.sh "latest" "${{secrets.DOCKER_USERNAME}}"
      - run: curl ${{secrets.RENDER_DEPLOY_WEBHOOK_URL}}
